export const SANSPAPER_REDUCER_ACTIONS = {
  UPDATE_SANSPAPER_USER: 'sanspaperActions/UPDATE_SANSPAPER_USER',
  UPDATE_SANSPAPER_USER_LIST: 'sanspaperActions/UPDATE_SANSPAPER_USER_LIST',
  UPDATE_SANSPAPER_ORGANISATION:
    'sanspaperActions/UPDATE_SANSPAPER_ORGANISATION',
  UPDATE_SANSPAPER_ORGANISATION_PATH:
    'sanspaperActions/UPDATE_SANSPAPER_ORGANISATION_PATH',
  UPDATE_UPVISE_TEMPLATE_PATH: 'sanspaperActions/UPDATE_UPVISE_TEMPLATE_PATH',
};
