export const screens = {
  InitialScreen: 'InitialScreen',
  LoginScreen: 'LoginScreen',
  MainScreen: 'MainScreen',
  LinkedItems: 'LinkedItems',
  OfflineLinkedItems: 'OfflineLinkedItems',
  FormScreen: 'FormScreen',
  OfflineFormScreen: 'OfflineFormScreen',
  OfflineFormFieldsScreen: 'OfflineFormFieldsScreen',
  FormFieldsScreen: 'FormFieldsScreen',
  ActivityIndicatorOverlay: 'ActivityIndicatorOverlay',
  RightButton: 'RightButton',
  ProfileScreen: 'ProfileScreen',
  MapScreen: 'MapScreen',
  SelectMap: 'SelectMap',
  HeaderScreen: 'HeaderScreen',
  SyncButton: 'SyncButton',
};
